<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="kmohd-lp" ignored="0" name="RetryMulitple" tests="10" failures="2" timestamp="12 Dec 2018 14:35:21 GMT" time="0.052" errors="0">
  <testcase name="Test1" time="0.009" classname="tryanalyzer.Test002">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="tryanalyzer.Test002">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="tryanalyzer.Test002">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="tryanalyzer.Test002">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="tryanalyzer.Test002">
    <failure type="java.lang.AssertionError" message="expected [9] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [9] but found [10]
at tryanalyzer.Test002.Test1(Test002.java:12)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.001" classname="tryanalyzer.Test002">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="tryanalyzer.Test002">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="tryanalyzer.Test002">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="tryanalyzer.Test002">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="tryanalyzer.Test002">
    <failure type="java.lang.AssertionError" message="expected [11] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [11] but found [10]
at tryanalyzer.Test002.Test2(Test002.java:19)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
</testsuite> <!-- RetryMulitple -->
